// vue_ui/src/06_shared/ui/Button.vue
<template>
    <div class="card flex justify-center">
        <Button v-slot="slotProps" asChild>
            <button v-bind="slotProps.a11yAttrs" :class="theme">
                SIGN UP
            </button>
        </Button>
    </div>
</template>

<script setup lang="ts">
import Button from '@/volt/Button.vue';
import { twMerge } from 'tailwind-merge';
import { useAttrs } from 'vue';
const attrs = useAttrs()
const { class: className }  = attrs// to ensure attrs are passed down to the button

const theme = twMerge(
    `
        text-white
        pt-0.5 pb-[3px]            
        sm:pt-1 sm:pb-[5px] 
        cursor-pointer 
        transition-all 
        duration-100 
        ease-out
        rounded-[11px] 
        flex items-center justify-center 
        box-border
        
        shadow-[0_3px_0_0_theme(colors.level-3),_0_0px_10px_rgba(0,0,0,0.4),_0_2px_4px_rgba(0,0,0,0.3)]
        sm:shadow-[0_5px_0_0_theme(colors.level-3),_0_0px_15px_rgba(0,0,0,0.55),_0_4px_8px_rgba(0,0,0,0.45)]
        
        hover:shadow-[0_6px_0_0_theme(colors.level-3),0_0px_15px_rgba(255,255,255,0.25),0_4px_8px_rgba(255,255,255,0.15)]
        hover:text-shadow-[0_0_4px_rgba(255,255,255,0.8),_0_0_25px_rgba(255,255,255,0.4)]
        hover:[&_svg]:drop-shadow-[0_0_4px_rgba(255,255,255,0.8)]
        disabled:cursor-not-allowed
        disabled:opacity-50
        disabled:shadow-none
        disabled:hover:shadow-none
        disabled:hover:text-shadow-none
        disabled:[&_svg]:drop-shadow-none
        disabled:active:shadow-none
        disabled:active:translate-y-0
        transform translate-y-0
        active:translate-y-[3px]
        sm:active:translate-y-[5px]   
        active:shadow-[0_0px_0_0_theme(colors.level-3),0_0px_3px_rgba(0,0,0,0.1),0_1px_2px_rgba(0,0,0,0.05)] 
        
      `, attrs.class, `bg-${attrs.theme || 'level-2'}`
)

</script>

// new_ui/src/components/ui/button.tsx
import * as React from 'react'
import { cn } from '@/lib/utils'

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  isActive?: boolean // Если true — кнопка зафиксирована в нажатом состоянии
}

export function Button({
  onClick,
  className,
  disabled = false,
  isActive,
  children,
  ...props
}: ButtonProps) {
  const isToggleMode = isActive !== undefined
  const isActiveState = isToggleMode && isActive

  return (
    <button
      onClick={onClick}
      disabled={disabled}
      className={cn(
        `
        btn-3d
        pt-0.5 pb-0.75 sm:pt-1 sm:pb-1.25 
        px-3 py-1.5
        cursor-pointer 
        transition-all 
        text-text-main
        [&_svg]:text-text-main
        duration-100 
        ease-out
        rounded-(--rounded-std) 
        flex items-center justify-center gap-2
        box-border
        border border-accent/40
        bg-level-2
        text-sm font-medium
        
        hover:text-shadow-[0_0_4px_rgba(255,255,255,0.8),0_0_25px_rgba(255,255,255,0.4)]
        hover:[&_svg]:drop-shadow-[0_0_4px_rgba(255,255,255,0.8)]

        disabled:cursor-not-allowed
        disabled:opacity-50
        disabled:shadow-none
        disabled:hover:shadow-none
        disabled:hover:text-shadow-none
        disabled:[&_svg]:drop-shadow-none
      `,
        isActiveState && 'btn-3d-active',
        className,
      )}
      {...props}
    >
      {children}
    </button>
  )
}

export default Button
