// front-end/src/6_shared/ui/currency-selector/CurrencySelector.vue
<script setup lang="ts">
import { ref } from 'vue'
import type { SelectRootProps } from 'radix-vue'
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/6_shared/ui/select'
import { cn } from '@/6_shared/lib/utils'

// Hardcoding currencies locally to prevent dependency issues, as constants weren't fully migrated
const CURRENCIES = [
  { code: 'USD', symbol: '$', name: 'US Dollar' },
  { code: 'EUR', symbol: '€', name: 'Euro' },
  { code: 'RUB', symbol: '₽', name: 'Russian Ruble' }
]

const props = withDefaults(defineProps<{
  value?: string
  name: string
  placeholder?: string
  currencies?: 'custom' | 'all'
  variant?: 'default' | 'small'
  valid?: boolean
  class?: string
}>(), {
  placeholder: 'Select currency',
  currencies: 'all',
  variant: 'default',
  valid: true
})

const emit = defineEmits<{
  (e: 'update:value', value: string): void
  (e: 'currencySelect', currency: any): void
}>()

const handleValueChange = (newValue: string) => {
  const fullCurrencyData = CURRENCIES.find((curr) => curr.code === newValue)
  if (fullCurrencyData) {
    emit('update:value', newValue)
    emit('currencySelect', fullCurrencyData)
  }
}
</script>

<template>
  <Select :model-value="value" @update:model-value="handleValueChange" :name="name" :data-valid="valid">
    <SelectTrigger
      :class="cn(
        'w-full',
        variant === 'small' && 'w-fit gap-2',
        'border-0 bg-level-2 active:ring-1 rounded-md',
        !valid && 'ring-destructive',
        props.class
      )"
      :data-valid="valid"
    >
      <SelectValue :placeholder="placeholder">
        <template v-if="value && variant === 'small'">
          <span>{{ value }}</span>
        </template>
      </SelectValue>
    </SelectTrigger>
    <SelectContent class="bg-level-2 border-0">
      <SelectGroup>
        <SelectItem
          v-for="currency in CURRENCIES"
          :key="currency.code"
          :value="currency.code"
          class="focus:bg-level-3"
        >
          <div class="flex items-center w-full gap-2">
            <span class="text-sm text-text-main text-center w-6 shrink-0">{{ currency.symbol }}</span>
            <span class="text-sm text-text-main w-8 text-left">{{ currency.code }}</span>
            <span class="text-sm text-text-main">{{ currency.name }}</span>
          </div>
        </SelectItem>
      </SelectGroup>
    </SelectContent>
  </Select>
</template>

// new_ui/src/components/ui/currency-selector.tsx
import React from 'react'

import type { SelectProps } from '@radix-ui/react-select'
import type { Currency } from '@/types/utils'
import { cn } from '@/lib/utils'

// shadcn
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import CURRENCIES from '@/lib/constants/currencies'

// types

interface CurrencySelectProps extends Omit<SelectProps, 'onValueChange'> {
  onValueChange?: (value: string) => void
  onCurrencySelect?: (currency: Currency) => void
  name: string
  placeholder?: string
  currencies?: 'custom' | 'all'
  variant?: 'default' | 'small'
  valid?: boolean
  className?: string
}

// Переменная-заглушка со списком валют

const CurrencySelectComponent = React.forwardRef<
  HTMLButtonElement,
  CurrencySelectProps
>(
  (
    {
      value,
      onValueChange,
      onCurrencySelect,
      name,
      placeholder = 'Select currency',
      currencies = 'all',
      variant = 'default',
      valid = true,
      className = '',
      ...props
    },
    ref,
  ) => {
    const [selectedCurrency, setSelectedCurrency] =
      React.useState<Currency | null>(null)

    // Используем заглушку напрямую
    const uniqueCurrencies = CURRENCIES

    const handleValueChange = (newValue: string) => {
      const fullCurrencyData = uniqueCurrencies.find(
        (curr) => curr.code === newValue,
      )
      if (fullCurrencyData) {
        setSelectedCurrency(fullCurrencyData)
        if (onValueChange) {
          onValueChange(newValue)
        }
        if (onCurrencySelect) {
          onCurrencySelect(fullCurrencyData)
        }
      }
    }

    void selectedCurrency

    return (
      <Select
        value={value}
        onValueChange={handleValueChange}
        {...props}
        name={name}
        data-valid={valid}
      >
        <SelectTrigger
          className={cn(
            'w-full',
            variant === 'small' && 'w-fit gap-2',
            'border-0 bg-level-2 active:ring-1 rounded-md',
            !valid && 'ring-destructive',
            className,
          )}
          data-valid={valid}
          ref={ref}
        >
          {value && variant === 'small' ? (
            <SelectValue placeholder={placeholder}>
              <span>{value}</span>
            </SelectValue>
          ) : (
            <SelectValue placeholder={placeholder} />
          )}
        </SelectTrigger>
        <SelectContent className="bg-level-2 border-0">
          <SelectGroup className="">
            {uniqueCurrencies.map((currency) => (
              <SelectItem
                key={currency?.code}
                value={currency?.code || ''}
                className=" focus:bg-level-3"
              >
                <div className="flex items-center w-full gap-2">
                  <span className="text-sm text-text-main  text-center w-6 shrink-0">
                    {currency?.symbol}
                  </span>
                  <span className="text-sm text-text-main w-8 text-left">
                    {currency?.code}
                  </span>
                  <span className="hidden">{currency?.symbol}</span>
                  <span className="text-sm text-text-main">
                    {currency?.name}
                  </span>
                </div>
              </SelectItem>
            ))}
          </SelectGroup>
        </SelectContent>
      </Select>
    )
  },
)

CurrencySelectComponent.displayName = 'CurrencySelect'

const CurrencySelect = React.memo(CurrencySelectComponent)

export { CurrencySelect }
