// new_ui/src/components/dnd/ReorderRail.tsx
// features/playlist/components/dnd/ReorderRail.tsx
import { ChevronDown, ChevronUp, GripVertical } from 'lucide-react'
import { useSortable } from '@dnd-kit/sortable'
import { CSS } from '@dnd-kit/utilities'

export type ReorderMode = 'dnd' | 'arrows'

export function ReorderRail({
  id,
  mode,
  isFirst,
  isLast,
  isActive,
  onMove,
  children,
}: {
  id: string
  mode: ReorderMode
  isFirst: boolean
  isLast: boolean
  isActive: boolean
  onMove: (dir: 'up' | 'down') => void
  children: (isDragging: boolean) => React.ReactNode
}) {
  const {
    attributes,
    listeners,
    setNodeRef,
    transform,
    transition,
    isDragging,
  } = useSortable({ id, disabled: mode !== 'dnd' })

  return (
    <div
      ref={setNodeRef}
      style={{
        transform: CSS.Translate.toString(transform),
        transition: isDragging ? undefined : transition,
        // Плейсхолдер вместо летающей копии — реальный визуал в DragOverlay
        opacity: isDragging ? 0 : 1,
      }}
      className="flex items-stretch gap-3 "
    >
      <div className="flex-1 min-w-0">{children(isDragging)}</div>
      <div
        className={`flex flex-col items-center  justify-center w-6 shrink-0 cursor-grab active:cursor-grabbing rounded-sm bg-level-2  border border-level-3/15 ${
          mode === 'arrows' ? '' : ''
        } ${isActive ? 'block' : 'hidden'}`}
        {...attributes}
        {...listeners}
      >
        {mode === 'dnd' ? (
          <div
            aria-label="Drag to reorder"
            style={{ touchAction: 'none' }} // критично: только тут, не на карточке/списке
            className="w-full  flex items-center justify-center  text-text-placeholder hover:text-level-3 active:bg-level-1/40"
          >
            <GripVertical className="h-4 w-4" />
          </div>
        ) : (
          <>
            <button
              disabled={isFirst}
              onClick={() => onMove('up')}
              aria-label="Move up"
              className="flex-1  w-full flex items-center justify-center disabled:opacity-20 text-text-placeholder hover:text-level-3 active:bg-level-1/40"
            >
              <ChevronUp className="h-3.5 w-3.5" />
            </button>
            <div className="h-px w-3 bg-white/5" />
            <button
              disabled={isLast}
              onClick={() => onMove('down')}
              aria-label="Move down"
              className="flex-1  w-full flex items-center justify-center disabled:opacity-20 text-text-placeholder hover:text-level-3 active:bg-level-1/40"
            >
              <ChevronDown className="h-3.5 w-3.5" />
            </button>
          </>
        )}
      </div>
    </div>
  )
}

// front-end/src/4_features/manage-tracks/ui/ReorderRail.vue
<script setup lang="ts">
import { GripVerticalIcon, ChevronUpIcon, ChevronDownIcon } from 'lucide-vue-next'

const props = defineProps<{
  id: string
  mode: 'dnd' | 'arrows'
  isFirst: boolean
  isLast: boolean
  isActive: boolean
  isDragging?: boolean
}>()

const emit = defineEmits<{
  (e: 'move', dir: 'up' | 'down'): void
}>()
</script>

<template>
  <div 
    class="flex items-stretch gap-3 min-h-22"
    :style="{ opacity: isDragging ? 0 : 1 }"
  >
    <div class="flex-1 min-w-0">
      <slot :isDragging="isDragging" />
    </div>
    
    <div 
      :class="[
        'flex flex-col items-center justify-center w-6 shrink-0 rounded-sm bg-level-2 border border-level-3/15',
        isActive ? 'block' : 'hidden',
        mode === 'dnd' ? 'cursor-grab active:cursor-grabbing' : ''
      ]"
    >
      <template v-if="mode === 'dnd'">
        <div 
          aria-label="Drag to reorder"
          style="touch-action: none"
          class="w-full flex items-center justify-center text-text-placeholder hover:text-level-3 active:bg-level-1/40"
        >
          <GripVerticalIcon class="h-4 w-4" />
        </div>
      </template>
      <template v-else>
        <button
          :disabled="isFirst"
          @click="emit('move', 'up')"
          aria-label="Move up"
          class="flex-1 min-h-11 w-full flex items-center justify-center disabled:opacity-20 text-text-placeholder hover:text-level-3 active:bg-level-1/40"
        >
          <ChevronUpIcon class="h-3.5 w-3.5" />
        </button>
        <div class="h-px w-3 bg-white/5" />
        <button
          :disabled="isLast"
          @click="emit('move', 'down')"
          aria-label="Move down"
          class="flex-1 min-h-11 w-full flex items-center justify-center disabled:opacity-20 text-text-placeholder hover:text-level-3 active:bg-level-1/40"
        >
          <ChevronDownIcon class="h-3.5 w-3.5" />
        </button>
      </template>
    </div>
  </div>
</template>
